### ISSUE TITLE
Having something selected uses 100% CPU on one core

### ISSUE THREAD

**Issue by ip2k** [dmnd/rainbow-selection#3] opened 2015-06-04 20:45 UTC
Steps to repro: highlight a line or anything. Check CPU usage.

Is there a more efficient way to do this color fade animation? I really do like this plugin, but the performance hit for the value it brings (making me smile) is hard to justify sometimes :)

**Comment by dmnd** [comment] 2015-06-04 22:49
I can't reproduce this with Atom 0.205.0 on OS X 10.10.3. What are you using? If OS X, can you describe how you are measuring CPU usage?

**Comment by dmnd** [comment] 2017-09-03 00:13
I can't reproduce on Atom 1.19.3 on OS X 10.12.6, so I'm closing the issue.

Additionally, if this does cause a lot of CPU usage it's likely a bug in Atom, not this extension. The source code is literally a [single CSS animation](https://github.com/dmnd/rainbow-selection/blob/master/styles/rainbow-selection.atom-text-editor.less). If that causes excessive resource consumption, you should report it to Atom core.

**Closed as completed by dmnd** 2017-09-03 00:13 UTC
